name: Process changes to the "My Clippings.txt" file

on:
  push:
    branches:
      - master

# using filthy hacks by copying files from other branches (by name) and then deleting them again

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Create annotation files in temporary branch
        run: |
          git fetch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan temp
          git rm -rf .
          rm -f *
          ls -lia
          git checkout master -- process.py "My Clippings.txt" .gitattributes .gitconfig
          python process.py
          git add -A
          git commit -m "init"
      # - name: Merge new annotations with notes branch
      #   run: |
      #     git checkout notes
      #     git checkout master -- process.py "My Clippings.txt" .gitattributes .gitconfig
      #     git merge --allow-unrelated-histories --no-commit temp
      #     rm -rf process.py "My Clippings.txt" .gitattributes .gitconfig
      #     git add -A
      #     git commit -m "update notes"
      - name: Merge old stuff into temp branch
        run: |
          git merge --allow-unrelated-histories
          git rm -rf  -- process.py "My Clippings.txt" .gitattributes .gitconfig
          rm -rf process.py "My Clippings.txt" .gitattributes .gitconfig
          git add -A
          git commit -m "remove temp files"
      - name: Merge notes into notes branch
        run: |
          git checkout notes
          git merge temp
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: notes